# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: UseDotNet@2
  displayName: 'Use .NET 6.0.400 SDK'
  inputs:
    packageType: 'sdk'
    version: 6.0.400

- task: DotNetCoreCLI@2
  displayName: 'Pack Templates'
  inputs:
    packagesToPack: 'FluentSearch.Plugin.Templates.csproj'
    command: pack
    outputDir: '$(Build.ArtifactStagingDirectory)/NuGet'
    verbosityPack: normal

- task: CmdLine@2
  displayName: 'Install templates'
  inputs:
    script: 'dotnet new -i $(Build.ArtifactStagingDirectory)/NuGet/*.nupkg'

- task: NuGetCommand@2
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'Blast.API'